service: serverless-studentapi-dynamodb

stage: ${opt:stage}

custom:
    dynamodb:
        start:
            port: 8000
            inMemory: true
            migrate: true
            migration: 
                dir: offline/migrations

provider:
    name: aws
    runtime: nodejs10.x
    timeout: 30
    custom:
    defaultStage: dev
    profiles:
      dev: devProfile
  

environment: 
    DYNAMODB_TABLE: Students
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
    
functions:
  get:
    handler: getStudents.handler
    events:
      - http:
          path: students
          method: get
          cors: true
          private: true

  create:
    handler: addStudent.handler
    events:
      - http:
          path: students
          method: post
          cors: true
          private: true
    