service: serverless-studentapi-dynamodb

stage: ${opt:stage}

custom:
    dynamodb:
        start:
            port: 8000
            inMemory: true
            migrate: true
            migration: 
                dir: offline/migrations

provider:
    name: aws
    runtime: nodejs10.x
    timeout: 30
    region: ${opt:region, 'ap-south-1'}
    custom:
    defaultStage: dev
    profiles:
      dev: devProfile
  

environment: 
    
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem

  DYNAMODB_TABLE: Students
    
functions:
  get:
    handler: students/getStudents.handler
    events:
      - http:
          path: /students
          method: get
          cors: true
        

  create:
    handler: students/addStudents.handler
    events:
      - http:
          path: /students
          method: post
          cors: true